version: '3.8'

services:
  api:
    build: .
    container_name: finance-dashboard-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=super_secret_jwt_key_for_assignment
      - DATABASE_URL=file:./dev.db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
